import pandas as pd
import numpy as np

# =================================================================
# 1. SETTINGS & PHYSICAL CONSTRAINTS
# =================================================================
PV_SETTINGS = {
    'AREA': 300, 
    'TILT_DEG': 7, 
    'EFF': 0.20, 
    'PR': 0.78, 
    'D': 0.005
}

# --- POWER ALLOCATION SETTINGS ---
ALLOCATION_SETTINGS = {
    'MANUAL_HEATING_SHARE': 0.5  # 0.5 = 50% to Heating, 50% to Cooling, this settings is overriden if the split mode is determined in the main tank scripts (this is a safety net).
}

# --- HEATING HEAT PUMP SETTINGS ---
HP_HEATING_SETTINGS = {
    'ETA_LO': 0.5, 
    'T_SINK_C': 45.0,
    'MAX_COP': 5.0  #
}

# --- COOLING HEAT PUMP SETTINGS ---
HP_COOLING_SETTINGS = {
    'ETA_LO': 0.5, 
    'T_SOURCE_C': 10.0,
    'MAX_COP': 4.5  #
}

# =================================================================
# 2. CORE LOGIC FUNCTION
# =================================================================
def calculate_thermal_potentials(df_weather, df_grid, split_mode='fixed', 
                                 h_demand=None, c_demand=None, manual_share=None, hp_max_h=115.0, hp_max_c=75.0):
    """
    Calculates potentials with explicit power division between HPs.
    """
    # --- A. Total PV Yield Calculation ---
    beta = np.radians(PV_SETTINGS['TILT_DEG'])
    df_weather['Direct_H'] = df_weather['GG'] - df_weather['GD']
    df_weather['I_poa'] = (df_weather['Direct_H'] * np.cos(beta)) + (df_weather['GD'] * (1 + np.cos(beta)) / 2)
    
    # Total Electrical kVA generated by PV
    total_pv_kva = (df_weather['I_poa'] * PV_SETTINGS['AREA'] * PV_SETTINGS['EFF'] * \
                    PV_SETTINGS['PR'] * (1 - PV_SETTINGS['D'])) / 1000
    
    # Total Electrical kVA from Grid
    total_grid_kva = df_grid['Grid_kVA'].values[:len(df_weather)]
    
    # Total Electrical kVA combined
    total_available_kva = total_pv_kva + total_grid_kva
    
    # --- B. POWER DIVISION LOGIC (Floor First) ---
    # Reserve 1.5 kVA for both HPs (Total 3.0) to ensure stratification maintenance
    active_pool = (total_available_kva - 3.0).clip(lower=0)

    if split_mode == 'proportional' and h_demand is not None and c_demand is not None:
        total_d = h_demand + c_demand
        ratio_h = np.where(total_d > 0, h_demand / total_d, 0.5)
    else:
        # Use the passed argument if it exists; otherwise, use the internal dictionary
        ratio_h = manual_share if manual_share is not None else ALLOCATION_SETTINGS['MANUAL_HEATING_SHARE']

    # Final kVA Assignment: Floor + (Remainder * Ratio)
    total_kva_h = 1.5 + (active_pool * ratio_h)
    total_kva_c = 1.5 + (active_pool * (1 - ratio_h))
    
    # --- C. COP CALCULATION ---
    t_amb_k = df_weather['T'] + 273.15
    
    # Heating COP
    t_sink_k = HP_HEATING_SETTINGS['T_SINK_C'] + 273.15
    raw_cop_h = HP_HEATING_SETTINGS['ETA_LO'] * (t_sink_k / (t_sink_k - t_amb_k + 0.1))
    cop_h = raw_cop_h.clip(lower=1.0, upper=HP_HEATING_SETTINGS['MAX_COP'])
    
    # Cooling COP
    t_source_k = HP_COOLING_SETTINGS['T_SOURCE_C'] + 273.15
    raw_cop_c = HP_COOLING_SETTINGS['ETA_LO'] * (t_source_k / (t_amb_k - t_source_k + 0.1))
    cop_c = raw_cop_c.clip(lower=1.0, upper=HP_COOLING_SETTINGS['MAX_COP'])
    
    # --- REALISTIC 3-STAGE FREE COOLING ---
    conditions = [
        df_weather['T'] < (HP_COOLING_SETTINGS['T_SOURCE_C'] - 2.0), # Total Free Cooling
        df_weather['T'] < HP_COOLING_SETTINGS['T_SOURCE_C']          # Partial Free Cooling
    ]
    choices = [15.0, 6.0]
    
    # Apply the choices based on conditions, otherwise keep the calculated cop_c
    cop_c = np.select(conditions, choices, default=cop_c)
    
    # =================================================================
    # --- D. DYNAMIC REDIRECTION LOGIC (TWO-STEP PASS) ---
    # =================================================================

    # --- PASS 1: Calculate raw thermal outputs based on the initial baseline split ratio ---
    raw_heating_thermal = total_kva_h * cop_h
    raw_cooling_thermal = total_kva_c * cop_c
    
    # --- PASS 2: Check saturation thresholds against physical machine sizes ---
    # Calculate the kVA needed to reach the physical machine ceiling
    kva_needed_h = hp_max_h / cop_h
    kva_slack_h = np.maximum(0, total_kva_h - kva_needed_h)
    # Only claim electrical slack if the heating pump is actively saturating past the ceiling
    kva_slack_h = np.where(raw_heating_thermal > hp_max_h, kva_slack_h, 0.0)

    kva_needed_c = hp_max_c / cop_c
    kva_slack_c = np.maximum(0, total_kva_c - kva_needed_c)
    # Only claim electrical slack if the cooling pump is actively saturating past the ceiling
    kva_slack_c = np.where(raw_cooling_thermal > hp_max_c, kva_slack_c, 0.0)

    # --- PASS 3: Cross-Redirect the Slack to the opposite machine pool ---
    final_kva_h = total_kva_h - kva_slack_h + kva_slack_c
    final_kva_c = total_kva_c - kva_slack_c + kva_slack_h

    # --- PASS 4: Calculate Final Outputs with Recycled Power ---
    df_weather['Potential_Heating_kW'] = np.minimum(final_kva_h * cop_h, hp_max_h)
    df_weather['Potential_Cooling_kW'] = np.minimum(final_kva_c * cop_c, hp_max_c)
    # Keeping your tracking metrics accurate for the orchestrator loops
    df_weather['Elec_kVA_Heating'] = final_kva_h
    df_weather['Elec_kVA_Cooling'] = final_kva_c
    df_weather['COP_Heating'] = cop_h
    df_weather['COP_Cooling'] = cop_c
    
    return df_weather.round(2)